name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches: 
      - main

permissions: 
    contents: write
    pages: write

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    steps:
      # Update Ubuntu packages
      - name: Update apt
        run: sudo apt update
      # Install additional Ubuntu packages
      - name: Install additional packages
        run: sudo apt-get install -y librsvg2-bin libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev

      # Checkout repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Setup Python with a fixed version
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt

      # Setup Quarto with fixed version
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
          version: 1.4.556
          

      # Render full profile
      - name: Publish to GitHub Pages (and render) 
        uses: quarto-dev/quarto-actions/render@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
          QUARTO_PROFILE: full
        #with:
        #  path: output/book/

      # Render Klausur profile
      - name: Publish to GitHub Pages (and render) 
        uses: quarto-dev/quarto-actions/render@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
          QUARTO_PROFILE: klausur
        #with:
        #  path: output/klausur/

      - name: Commit results to main branch
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "CI added changes `date +'%Y-%m-%d %H:%M:%S'`" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # WORKFLOW_GITHUB_TOKEN
          force: true
